name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pytest pytest-mock pytest-cov neo4j python-dotenv lxml testcontainers-neo4j
      - name: Run tests with coverage
        run: pytest --cov=wikipedia_analysis --cov-report=xml --cov-report=term-missing
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Required for private repositories or if you want to associate with a specific project
          fail_ci_if_error: true # Optional: Fail CI if Codecov upload fails